USE [master]
GO
/****** Object:  Database [Knila]    Script Date: 03-07-2025 21:38:00 ******/
CREATE DATABASE [Knila]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Knila', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Knila.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Knila_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Knila_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Knila] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Knila].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Knila] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Knila] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Knila] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Knila] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Knila] SET ARITHABORT OFF 
GO
ALTER DATABASE [Knila] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Knila] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Knila] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Knila] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Knila] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Knila] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Knila] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Knila] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Knila] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Knila] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Knila] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Knila] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Knila] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Knila] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Knila] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Knila] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Knila] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Knila] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Knila] SET  MULTI_USER 
GO
ALTER DATABASE [Knila] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Knila] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Knila] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Knila] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Knila] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Knila] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Knila] SET QUERY_STORE = ON
GO
ALTER DATABASE [Knila] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Knila]
GO
/****** Object:  Table [dbo].[Contact]    Script Date: 03-07-2025 21:38:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contact](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
	[Email] [nvarchar](150) NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[Address] [nvarchar](200) NULL,
	[City] [nvarchar](100) NULL,
	[State] [nvarchar](100) NULL,
	[Country] [nvarchar](100) NULL,
	[PostalCode] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 03-07-2025 21:38:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](255) NULL,
	[Password] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Contact] ON 
GO
INSERT [dbo].[Contact] ([Id], [FirstName], [LastName], [Email], [PhoneNumber], [Address], [City], [State], [Country], [PostalCode]) VALUES (11, N'Sanjay', N'M', N'sanjay.m@gmail.com', N'1234567890', N'akashya college', N'kinathukadavu', N'Tamil Nadu', N'India', N'600009')
GO
SET IDENTITY_INSERT [dbo].[Contact] OFF
GO
SET IDENTITY_INSERT [dbo].[User] ON 
GO
INSERT [dbo].[User] ([UserId], [UserName], [Password]) VALUES (1, N'TestUser', N'Welcome@123')
GO
SET IDENTITY_INSERT [dbo].[User] OFF
GO
USE [master]
GO
ALTER DATABASE [Knila] SET  READ_WRITE 
GO
